# Generated by Django 5.2.5 on 2025-08-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangarin', '0002_alter_note_content_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
