# Generated by Django 5.2.5 on 2025-08-27 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangarin', '0003_alter_category_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
